[package]
name = "ethereal-interpreter"
version = "0.1.0"
authors = ["bIgBV <bhargav.voleti93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "0.1.8"